name: Build
run-name: Build d64
on: [push]
jobs:
  build:
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y vice
          curl -s "https://get.sdkman.io" | bash
          source ~/.sdkman/bin/sdkman-init.sh
          sdk version
          sdk install java
          sdk install jbang
          which java
          which jbang
      - name: Make
        run: |
          source ~/.sdkman/bin/sdkman-init.sh
          sdk version
          which java
          which jbang
          make catfox.d64
      - name: Stage pages site
        run: cp catfox.d64 site/
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - run: |
          echo "Job status: ${{ job.status }}"

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4